services:
  mongo_db:
    image: mongo:latest
    container_name: library_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: books
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    container_name: library_api
    ports:
      - "8008:8000"
    environment:
      - MONGO_URI=mongodb://mongo_admin:password@mongo_db:27017
      - MONGO_DATABASE=books
    depends_on:
      - mongo_db
    volumes:
      - .:/app
    command: python main.py

volumes:
  mongo_data:
