"""Book business logic."""

import math

from models.book import BookStatus
from repository.book_repository import BookRepository
from schemas.book import BookCreate


class BookService:
    """Service for book operations."""

    def __init__(self, repository: BookRepository) -> None:
        self._repo = repository

    def get_all(
        self,
        *,
        status: BookStatus | None = None,
        author: str | None = None,
        sort_by: str | None = None,
        sort_order: str = "asc",
        page: int = 1,
        size: int = 10,
    ) -> dict:
        """Get books with page-based pagination."""
        items, total = self._repo.get_all(
            status=status,
            author=author,
            sort_by=sort_by,
            sort_order=sort_order,
            page=page,
            size=size,
        )
        total_pages = math.ceil(total / size) if size else 0
        return {
            "items": items,
            "page": page,
            "size": size,
            "total": total,
            "total_pages": total_pages,
        }

    def get_by_id(self, book_id: str) -> dict | None:
        """Get a book by ID (MongoDB ObjectId string)."""
        return self._repo.get_by_id(book_id)

    def create(self, payload: BookCreate) -> dict:
        """Create a new book (_id generated by MongoDB)."""
        book_dict = {
            "title": payload.title,
            "author": payload.author,
            "description": payload.description,
            "status": payload.status.value,
            "year": payload.year,
        }
        return self._repo.add(book_dict)

    def delete(self, book_id: str) -> bool:
        """Delete a book by ID. Returns True if removed, False if not found."""
        return self._repo.delete(book_id)
